# Voice mappings for EdgeEngine.
edge_default_voice_mapping = {
    'en': 'en-US-EmmaMultilingualNeural',
    'es': 'es-ES-ElviraNeural',
    'fr': 'fr-FR-DeniseNeural',
    'de': 'de-DE-SeraphinaMultilingualNeural',
    'af': 'af-ZA-AdriNeural',
    'am': 'am-ET-MekdesNeural',
    'ar': 'ar-SA-ZariyahNeural',
    'az': 'az-AZ-BanuNeural',
    'bg': 'bg-BG-KalinaNeural',
    'bn': 'bn-BD-NabanitaNeural',
    'bs': 'bs-BA-VesnaNeural',
    'ca': 'ca-ES-JoanaNeural',
    'cs': 'cs-CZ-VlastaNeural',
    'cy': 'cy-GB-NiaNeural',
    'da': 'da-DK-ChristelNeural',
    'el': 'el-GR-AthinaNeural',
    'et': 'et-EE-AnuNeural',
    'fa': 'fa-IR-DilaraNeural',
    'fi': 'fi-FI-NooraNeural',
    'fil': 'fil-PH-BlessicaNeural',
    'ga': 'ga-IE-OrlaNeural',
    'gl': 'gl-ES-SabelaNeural',
    'gu': 'gu-IN-DhwaniNeural',
    'he': 'he-IL-HilaNeural',
    'hi': 'hi-IN-SwaraNeural',
    'hr': 'hr-HR-GabrijelaNeural',
    'hu': 'hu-HU-NoemiNeural',
    'id': 'id-ID-GadisNeural',
    'is': 'is-IS-GudrunNeural',
    'it': 'it-IT-ElsaNeural',
    'ja': 'ja-JP-NanamiNeural',
    'jv': 'jv-ID-SitiNeural',
    'ka': 'ka-GE-EkaNeural',
    'kk': 'kk-KZ-AigulNeural',
    'km': 'km-KH-SreymomNeural',
    'kn': 'kn-IN-SapnaNeural',
    'ko': 'ko-KR-SunHiNeural',
    'lo': 'lo-LA-KeomanyNeural',
    'lt': 'lt-LT-OnaNeural',
    'lv': 'lv-LV-EveritaNeural',
    'mk': 'mk-MK-MarijaNeural',
    'ml': 'ml-IN-SobhanaNeural',
    'mn': 'mn-MN-YesuiNeural',
    'mr': 'mr-IN-AarohiNeural',
    'ms': 'ms-MY-YasminNeural',
    'mt': 'mt-MT-GraceNeural',
    'my': 'my-MM-NilarNeural',
    'nb': 'nb-NO-PernilleNeural',
    'ne': 'ne-NP-HemkalaNeural',
    'nl': 'nl-NL-FennaNeural',
    'pl': 'pl-PL-ZofiaNeural',
    'ps': 'ps-AF-LatifaNeural',
    'pt': 'pt-BR-FranciscaNeural',
    'ro': 'ro-RO-AlinaNeural',
    'ru': 'ru-RU-SvetlanaNeural',
    'si': 'si-LK-ThiliniNeural',
    'sk': 'sk-SK-ViktoriaNeural',
    'sl': 'sl-SI-PetraNeural',
    'so': 'so-SO-UbaxNeural',
    'sq': 'sq-AL-AnilaNeural',
    'sr': 'sr-RS-SophieNeural',
    'su': 'su-ID-TutiNeural',
    'sv': 'sv-SE-SofieNeural',
    'sw': 'sw-KE-ZuriNeural',
    'ta': 'ta-IN-PallaviNeural',
    'te': 'te-IN-ShrutiNeural',
    'th': 'th-TH-PremwadeeNeural',
    'tr': 'tr-TR-EmelNeural',
    'uk': 'uk-UA-PolinaNeural',
    'ur': 'ur-PK-UzmaNeural',
    'uz': 'uz-UZ-MadinaNeural',
    'vi': 'vi-VN-HoaiMyNeural',
    'zh': 'zh-CN-XiaoxiaoNeural',
    'zu': 'zu-ZA-ThandoNeural',
}

# Voice mappings for KokoroEngine.
kokoro_default_voice_mapping = {
    'en': 'af_heart',    # American English
    'ja': 'jf_alpha',    # Japanese
    'zh': 'zf_xiaobei',  # Mandarin Chinese
    'es': 'ef_dora',     # Spanish
    'fr': 'ff_siwis',    # French
    'hi': 'hf_alpha',    # Hindi
    'it': 'if_sara',     # Italian
    'pt': 'pf_dora',     # Brazilian Portuguese
}
